{{- if and .Values.configServer.enabled (eq .Values.configSourceKind "http") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-perf-gateway.configServer.fullname" . }}
  labels:
    {{- include "envoy-perf-gateway.configServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.configServer.service.type }}
  ports:
    - name: http
      port: {{ .Values.configServer.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "envoy-perf-gateway.configServer.selectorLabels" . | nindent 4 }}
{{- end }}
