{{- if and .Values.configServer.enabled (eq .Values.configSourceKind "http") }}
{{- if and .Values.configServer.persistence.enabled (not .Values.configServer.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "envoy-perf-gateway.configServer.fullname" . }}
  labels:
    {{- include "envoy-perf-gateway.configServer.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.configServer.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.configServer.persistence.size }}
  {{- if .Values.configServer.persistence.storageClassName }}
  storageClassName: {{ .Values.configServer.persistence.storageClassName }}
  {{- end }}
{{- end }}
{{- end }}
