{{- if eq .Values.configSourceKind "http" }}
{{- if not .Values.configApiTokenExistingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envoy-perf-gateway.fullname" . }}
  labels:
    {{- include "envoy-perf-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  config-api-token: {{ .Values.configApiToken | quote }}
{{- end }}
{{- end }}
