apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-perf-gateway.fullname" . }}
  labels:
    {{- include "envoy-perf-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "envoy-perf-gateway.selectorLabels" . | nindent 4 }}
